# Generated by Django 5.1.5 on 2026-01-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='descrition',
            new_name='description',
        ),
    ]
